/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kannan' at '7/6/18 3:26 PM' with Gradle 3.0
 *
 * @author Kannan, @date 7/6/18 3:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
